spring:
  application:
    name: mslabel
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://mslabel-db.cyc2p8ojoa5l.ap-northeast-2.rds.amazonaws.com:3306/mslabel
    username: admin
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  packages-to-scan: com.labelPrint.mslabel.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

application:
  security:
    jwt:
      secret-key: ac68bcfdacdaf425efb13abfc8b09761f0efea8559d655718e06d89c081bbde6
      expiration: 86400000 # 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
